"""Does the moving-cavity workflow emit a partition with duplicate element ownership?

The crash cluster straddles ranks 1603/1606 (the two that reported the blow-up), and
elements 39028/39029 appear in the OWNED portion of both ranks' my_list files. In
FESOM's decomposition every element and node must be owned by exactly one rank, with
the others carrying it in the halo (eDim). If ownership is duplicated, two ranks
integrate the same element and exchange_elem then has an inconsistent view - which is
a mechanism that overwrites correctly-computed UV values after update_vel has run.

dist_NNNN is regenerated by the workflow every time the cavity moves, which fits the
observation that this failure mode never appeared in a decade of fixed-mesh FESOM.

Census the whole partition, and every cycle's partition, before concluding anything.
"""
import glob, sys, numpy as np

CO = "/work/ab0246/a270092/runtime/awiesm3-develop-is/fgdbg02/couple"


def census(dist):
    files = sorted(glob.glob(f"{dist}/my_list*.out"))
    if not files:
        return None
    nod_owners, elem_owners = {}, {}
    for f in files:
        v = np.fromstring(open(f).read(), dtype=np.int64, sep=' ')
        if v.size < 4:
            continue
        rank, myn, edn = int(v[0]), int(v[1]), int(v[2])
        nodes = v[3:3 + myn + edn]
        p = 3 + myn + edn
        for t in nodes[:myn]:
            nod_owners[int(t)] = nod_owners.get(int(t), 0) + 1
        if v.size > p + 2:
            mye, ede = int(v[p]), int(v[p + 1])
            els = v[p + 2:p + 2 + mye + ede]
            for t in els[:mye]:
                elem_owners[int(t)] = elem_owners.get(int(t), 0) + 1
    return nod_owners, elem_owners


for tag in ("1901", "1902", "1903", "1904", "1905", "1906"):
    dist = glob.glob(f"{CO}/submesh_{tag}-12-31T00:00:00/dist_*")
    if not dist:
        print(f"{tag}: no dist_ dir")
        continue
    r = census(dist[0])
    if r is None:
        print(f"{tag}: no my_list files in {dist[0]}")
        continue
    no, eo = r
    ndup = [k for k, c in no.items() if c > 1]
    edup = [k for k, c in eo.items() if c > 1]
    print(f"\n=== submesh {tag}  ({dist[0].split('/')[-1]}) ===")
    print(f"  nodes with an owner    : {len(no):8d}   owned by >1 rank: {len(ndup):6d}")
    print(f"  elements with an owner : {len(eo):8d}   owned by >1 rank: {len(edup):6d}")
    if edup:
        edup.sort()
        print(f"    duplicate-owned elements, first 20: {edup[:20]}")
        print(f"    max multiplicity: {max(eo[k] for k in edup)}")
        for t in (39028, 39029, 39030):
            print(f"    elem {t}: owned by {eo.get(t)} rank(s)")
    if ndup:
        ndup.sort()
        print(f"    duplicate-owned nodes, first 20: {ndup[:20]}")
